#!/usr/bin/env sh

scriptdir=$(dirname $0)

while getopts ":n:e:u:do" opt; do
    case $opt in
        n)
            export FACTER_myname=${OPTARG}
            ;;
        e)
            export FACTER_myemail=$OPTARG
            ;;
        u)
	    if $(getent passwd $OPTARG 1> /dev/null 2>&1); then
		export FACTER_myuser=$(id -u $OPTARG)
		export FACTER_mygroup=$(id -g $OPTARG)
		export FACTER_myhome="/home/$OPTARG"
	    else
		echo "Argument to -${opt} should be a valid username."
		exit -1
	    fi
            ;;
	d)
	    puppet_extra_args="${puppet_extra_args} --debug"
	    ;;
	o)
	    puppet_extra_args="${puppet_extra_args} --noop"
	    ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
		echo "Ex. usage: $0 -n 'John Doe' -e john@doe.com -u john"
        ;;
	:)
	    echo "Option -$OPTARG requires an argument." >&2
		echo "Ex. usage: $0 -n 'John Doe' -e john@doe.com -u john"
	    exit 1
	    ;;
    esac

done

exec /opt/puppetlabs/bin/puppet apply --modulepath "${scriptdir}/../modules" --verbose "${scriptdir}/../manifests/init.pp" ${puppet_extra_args}
